name: enchantconveniences
version: '${version}'

main: daxz.dev.enchantconveniences.Enchantconveniences
bootstrapper: daxz.dev.enchantconveniences.EnchantconveniencesBootstrap
api-version: '26.1.2'
load: POSTWORLD
